# Generated by Django 5.2.16 on 2026-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_emailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='replylog',
            name='gmail_message_id',
            field=models.CharField(blank=True, default='', help_text='Gmail message ID for deduplication during polling.', max_length=255),
        ),
    ]
