# Generated by Django 5.2.16 on 2026-08-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resume_emaillog_resume_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, help_text='Which HR reply message this outbound email responds to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_sent', to='api.replylog'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='type',
            field=models.CharField(choices=[('initial', 'Initial'), ('reply', 'Reply')], default='initial', max_length=10),
        ),
        migrations.AddField(
            model_name='replylog',
            name='responded',
            field=models.BooleanField(default=False, help_text='Set True once the user sends a reply to this message.'),
        ),
    ]
